ci: Improvements
Upgrade checkout to v3.
Upgrade github-script to v6.
Upgrade CodeQL actions to v2.
Cleanup/formatting.

diff --git a/.github/workflows/dev.yml b/.github/workflows/dev.yml
--- a/.github/workflows/dev.yml
+++ b/.github/workflows/dev.yml
@@ -9,16 +9,16 @@ jobs:
   check:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout sources
-      uses: actions/checkout@v2
-    - name: Build
-      run: |
-        npm install
-        npm run all
-    - name: Check for uncommitted changes
-      # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
-      run: |
-        git diff --exit-code --stat -- . ':!node_modules' \
-        || (echo "##[error] found changed files after build. please 'npm run all'" \
-                 "and check in all changes" \
+      - name: Checkout sources
+        uses: actions/checkout@v3
+      - name: Build
+        run: |
+          npm install
+          npm run all
+      - name: Check for uncommitted changes
+        # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
+        run: |
+          git diff --exit-code --stat -- . ':!node_modules' \
+          || (echo "##[error] found changed files after build. please 'npm run all'" \
+              "and check in all changes" \
             && exit 1)
